### ISSUE TITLE
装了GroupManagerPlus-2.0.3貌似用不了，有报错

### ISSUE THREAD

**Issue by yan-color** [NyaaCat/NyaaUtils#30]
[10:15:50 WARN]: java.lang.NullPointerException
[10:15:50 WARN]:        at net.milkbowl.vault.chat.plugins.Chat_GroupManager.setPlayerValue(Chat_GroupManager.java:339)
[10:15:50 WARN]:        at net.milkbowl.vault.chat.plugins.Chat_GroupManager.setPlayerInfoString(Chat_GroupManager.java:242)
[10:15:50 WARN]:        at net.milkbowl.vault.chat.plugins.Chat_GroupManager.setPlayerPrefix(Chat_GroupManager.java:300)
[10:15:50 WARN]:        at net.milkbowl.vault.chat.Chat.setPlayerPrefix(Chat.java:114)
[10:15:50 WARN]:        at net.milkbowl.vault.chat.Chat.setPlayerPrefix(Chat.java:138)
[10:15:50 WARN]:        at cat.nyaa.nyaacore.utils.VaultUtils.setPlayerPrefix(VaultUtils.java:81)
[10:15:50 WARN]:        at cat.nyaa.nyaautils.CommandHandler.commandPrefix(CommandHandler.java:280)
[10:15:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:15:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:15:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:15:50 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[10:15:50 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:189)
[10:15:50 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.onCommand(CommandReceiver.java:163)
[10:15:50 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:15:50 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[10:15:50 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[10:15:50 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:15:50 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[10:15:50 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[10:15:50 WARN]:        at java.lang.Thread.run(Unknown Source)

emmmmmmmmmmm

**Comment by yan-color** [comment]
没事了
