### ISSUE TITLE
Error on reload

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#4]
On `/nu reload`

```
>nu reload
[17:26:46 WARN]: java.lang.NullPointerException
[17:26:46 WARN]:        at cat.nyaa.nyaautils.Configuration.deserialize(Configuration.java:69)
[17:26:46 WARN]:        at cat.nyaa.nyaautils.CommandHandler.commandReload(CommandHandler.java:238)
[17:26:46 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:26:46 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:26:46 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:26:46 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:26:46 WARN]:        at cat.nyaa.utils.CommandReceiver.acceptCommand(CommandReceiver.java:157)
[17:26:46 WARN]:        at cat.nyaa.utils.CommandReceiver.onCommand(CommandReceiver.java:133)
[17:26:46 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:26:46 WARN]:        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:91)
[17:26:46 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[17:26:46 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[17:26:46 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
[17:26:46 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
[17:26:46 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[17:26:46 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[17:26:46 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by phoenixlzx** [comment]
On `/nu enchant`

[18:24:55 INFO]: phoenixlzx issued server command: /nu enchant
[18:24:55 WARN]: java.lang.NullPointerException
[18:24:55 WARN]:        at cat.nyaa.nyaautils.CommandHandler.commandEnchant(CommandHandler.java:57)
[18:24:55 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:24:55 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:24:55 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:24:55 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[18:24:55 WARN]:        at cat.nyaa.utils.CommandReceiver.acceptCommand(CommandReceiver.java:157)
[18:24:55 WARN]:        at cat.nyaa.utils.CommandReceiver.onCommand(CommandReceiver.java:133)
[18:24:55 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:24:55 WARN]:        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:91)
[18:24:55 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:24:55 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:24:55 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[18:24:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[18:24:55 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
