### ISSUE TITLE
/nu realm 创建地区时出错

### ISSUE THREAD

**Issue by timeance** [NyaaCat/NyaaUtils#63]
服务端版本：`git-Paper-597 (MC: 1.13.2)`
插件版本：`NyaaCore-v6.3.329-mc1.13.2` `NyaaUtils-v6.1.245-mc1.13.2`
创建地区时发生了错误，只能直接修改配置文件来创建地区，请问是因为什么原因呢？
报错如下：
>
[00:40:53 INFO]: zariba issued server command: /nu realm create sky_city private test  
[00:40:53 WARN]: java.lang.RuntimeException: Failed to invoke subcommand  
[00:40:53 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:214)  
[00:40:53 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:205)  
[00:40:53 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.onCommand(CommandReceiver.java:180)  
[00:40:53 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[00:40:53 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[00:40:53 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[00:40:53 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:40:53 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[00:40:53 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[00:40:53 WARN]:        at java.lang.Thread.run(Thread.java:748)
[00:40:53 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[00:40:53 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:40:53 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:40:53 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:40:53 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[00:40:53 WARN]:        at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:207)
[00:40:53 WARN]:        ... 18 more
[00:40:53 WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
[00:40:53 WARN]:        at cat.nyaa.nyaautils.realm.RealmCommands.commandCreate(RealmCommands.java:65)
[00:40:53 WARN]:        ... 23 more

**Comment by timeance** [comment]
好了...是FAWE插件的问题，更新了之后就好了，抱歉打扰了...
