### ISSUE TITLE
与新版WorldEdit不兼容导致reload失败

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/NyaaUtils#68]
```
[10:47:58 INFO]: Ghost_chu issued server command: /nu reload
[10:47:58 INFO]: [NyaaUtils] Now using language: zh_CN
[10:47:58 WARN]: java.lang.ClassCastException: class com.sk89q.worldedit.bukkit.WorldEditPlugin cannot be cast to class com.sk89q.worldedit.bukkit.WorldEditPlugin (com.sk89q.worldedit.bukkit.WorldEditPlugin is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @845ffda; com.sk89q.worldedit.bukkit.WorldEditPlugin is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7d3ba998)
[10:47:58 WARN]: at cat.nyaa.nyaautils.NyaaUtils.onEnable(NyaaUtils.java:95)
[10:47:58 WARN]: at cat.nyaa.nyaautils.CommandHandler.commandReload(CommandHandler.java:199)
[10:47:58 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:47:58 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:47:58 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:47:58 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:47:58 WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver$SubCommandInfo.callCommand(CommandReceiver.java:78)
[10:47:58 WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:325)
[10:47:58 WARN]: at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.onCommand(CommandReceiver.java:296)
[10:47:58 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:47:58 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:47:58 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1925)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1191)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1184)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1160)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[10:47:58 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[10:47:58 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ReinWD** [comment]
应该是reload的问题 重启大概就解决了？
